"""
pdf_export.py
-------------
시험지 / 결과 리포트를 PDF 로 내보내는 모듈. (reportlab 사용)

한글 표시를 위해 fonts/ 폴더의 나눔스퀘어라운드 폰트를 등록한다.
문제 스키마는 ai_quiz.py 와 동일: type = "mc" | "written".
"""

import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.cidfonts import UnicodeCIDFont
from reportlab.lib.colors import black, grey, red, green, Color

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FONT_DIR = os.path.join(BASE_DIR, "fonts")
LABELS = ["A", "B", "C", "D", "E"]

# 사용자가 고를 수 있는 서체 (한글 렌더 가능한 것만)
_FONTS_READY = {}


def _register_fonts():
    """서체 등록(한 번만). 반환: {style: (bold_font, regular_font)} 딕셔너리."""
    global _FONTS_READY
    if _FONTS_READY:
        return _FONTS_READY
    reg = {}
    # 둥근고딕 (프로젝트 TTF)
    try:
        pdfmetrics.registerFont(TTFont("NanumB", os.path.join(FONT_DIR, "NanumSquareRoundB.ttf")))
        pdfmetrics.registerFont(TTFont("NanumR", os.path.join(FONT_DIR, "NanumSquareRoundR.ttf")))
        reg["round"] = ("NanumB", "NanumR")
    except Exception:
        reg["round"] = ("Helvetica-Bold", "Helvetica")
    # 명조 / 고딕 (reportlab 내장 CJK CID 폰트) — 폰트명 정확히!
    for style, name in (("myeongjo", "HYSMyeongJo-Medium"), ("gothic", "HYGothic-Medium")):
        try:
            pdfmetrics.registerFont(UnicodeCIDFont(name))
            reg[style] = (name, name)
        except Exception:
            reg[style] = reg["round"]
    _FONTS_READY = reg
    return reg


def _pick_fonts(style):
    reg = _register_fonts()
    return reg.get(style, reg["round"])


def _wrap_w(c, text, font, size, maxw):
    """폭(maxw) 기준 줄바꿈. 한글은 글자 단위, 영문은 되도록 단어 단위."""
    text = str(text or "")
    lines, cur, last_space = [], "", -1
    for ch in text:
        trial = cur + ch
        if c.stringWidth(trial, font, size) > maxw and cur:
            if last_space > 0 and ch != " ":
                lines.append(cur[:last_space].rstrip())
                cur = cur[last_space:].lstrip() + ch
            else:
                lines.append(cur)
                cur = ch
            last_space = -1
        else:
            cur = trial
            if ch == " ":
                last_space = len(cur) - 1
    if cur:
        lines.append(cur)
    return lines or [""]


def _watermark(c, w, h, text="VoQuiz 무료"):
    c.saveState()
    c.setFillColor(Color(0.6, 0.6, 0.6, alpha=0.12))
    c.setFont("Helvetica-Bold", 60)
    c.translate(w / 2, h / 2)
    c.rotate(35)
    c.drawCentredString(0, 0, text)
    c.restoreState()
    _logo_watermark(c, w, h)


_FADED_LOGO = None  # 우하단 워터마크용 반투명 로고 (한 번만 생성)


def _get_faded_logo():
    """VoQuiz 로고를 반투명하게 만들어 임시 파일로 캐시(무료 PDF 우하단 워터마크)."""
    global _FADED_LOGO
    if _FADED_LOGO is not None:
        return _FADED_LOGO
    try:
        from PIL import Image
        import tempfile
        src = os.path.join(BASE_DIR, "static", "VoQuiz_Logo_Light.png")
        im = Image.open(src).convert("RGBA")
        alpha = im.split()[3].point(lambda a: int(a * 0.28))  # 28% 불투명도
        im.putalpha(alpha)
        out = os.path.join(tempfile.gettempdir(), "vocashot_wm_logo.png")
        im.save(out)
        _FADED_LOGO = (out, im.width / im.height)
    except Exception:
        _FADED_LOGO = ("", 0)
    return _FADED_LOGO


def _logo_watermark(c, w, h):
    """우하단에 반투명 로고 스탬프."""
    path, ratio = _get_faded_logo()
    if not path or not ratio:
        return
    lw = 3.0 * cm
    lh = lw / ratio
    margin = 1.0 * cm
    try:
        c.drawImage(path, w - margin - lw, margin, width=lw, height=lh,
                    mask="auto", preserveAspectRatio=True)
    except Exception:
        pass


def create_quiz_pdf(quiz_list, filename, options=None, title_text=None):
    """
    옵션(options)에 따라 커스텀 시험지 PDF 생성.
    options: {title, font(round/myeongjo/gothic), font_size, columns(1/2),
              spacing, answer_key, header_fields, show_school, watermark}
    """
    o = dict(options or {})
    title_text = o.get("title") or title_text or "Vocabulary Quiz"
    style = o.get("font", "round")
    fs = int(o.get("font_size", 10))
    opt_fs = max(8, fs - 1)
    cols = 2 if int(o.get("columns", 1)) == 2 else 1
    gap = int(o.get("spacing", 8))
    title_font, body = _pick_fonts(style)

    c = canvas.Canvas(filename, pagesize=A4)
    w, h = A4
    ML, MR, MT, MB = 40, 40, 40, 56
    col_gap = 20
    col_w = (w - ML - MR - (col_gap * (cols - 1))) / cols

    def col_x(ci):
        return ML + ci * (col_w + col_gap)

    # ---------- 헤더 ----------
    def draw_header():
        c.setFillColor(black)
        c.setFont(title_font, 18)
        c.drawCentredString(w / 2, h - MT, title_text)
        top = h - MT - 20
        if o.get("show_school", True):
            c.setFont("Helvetica", 7)
            c.setFillColor(grey)
            c.drawCentredString(w / 2, top, "AI Generated by VoQuiz")
            c.setFillColor(black)
            top -= 10
        if o.get("header_fields", True):
            c.setFont(body, 9)
            c.line(ML, top - 4, w - MR, top - 4)
            c.drawString(ML, top - 20, "이름: ______________    날짜: ______________    점수: ______")
            top -= 30
        return top - 8

    kind = o.get("kind", "quiz")   # quiz(문제지) | answers(정답·해설지, 별도 파일)

    if kind == "answers":
        # ---------- 정답 & 해설 (별도 PDF) ----------
        if o.get("watermark"):
            _watermark(c, w, h)
        c.setFont(title_font, 18)
        c.setFillColor(black)
        c.drawCentredString(w / 2, h - MT, f"{title_text} — 정답 & 해설")
        y = h - MT - 30
        for i, q in enumerate(quiz_list):
            ans_label = ""
            if q.get("type") != "written":
                for idx, opt in enumerate(q.get("options", [])):
                    if opt == q.get("answer"):
                        ans_label = f"{LABELS[idx]}. "
                        break
            block = _wrap_w(c, f"   {q.get('explanation','')}", body, max(8, fs - 1), w - ML - MR)
            need = (fs + 4) + 11 * len(block) + 8
            if y - need < MB:
                c.showPage()
                if o.get("watermark"):
                    _watermark(c, w, h)
                y = h - MT
            c.setFont(title_font, fs)
            c.setFillColor(black)
            c.drawString(ML, y, f"{i+1}. {ans_label}{q.get('answer','')}")
            y -= fs + 3
            c.setFont(body, max(8, fs - 1))
            c.setFillColor(grey)
            for ln in block:
                c.drawString(ML, y, ln)
                y -= 11
            y -= 8
        c.save()
        return

    # ---------- 문제지 (정답 없음 — 정답은 별도 PDF) ----------
    if o.get("watermark"):
        _watermark(c, w, h)
    y = draw_header()
    ci = 0

    def newcol_or_page(need):
        nonlocal y, ci
        if y - need < MB:
            if ci < cols - 1:
                ci += 1
                y = h - MT - 4
            else:
                c.showPage()
                if o.get("watermark"):
                    _watermark(c, w, h)
                ci = 0
                y = h - MT - 10

    for i, q in enumerate(quiz_list):
        x = col_x(ci)
        qlines = _wrap_w(c, f"{i+1}. {q.get('question','')}", body, fs, col_w)
        opts = q.get("options", []) if q.get("type") != "written" else []
        need = (fs + 4) * len(qlines) + (opt_fs + 3) * len(opts) + (24 if q.get("type") == "written" else 0) + gap
        newcol_or_page(need)
        x = col_x(ci)
        c.setFillColor(black)
        c.setFont(body, fs)
        for ln in qlines:
            c.drawString(x, y, ln)
            y -= fs + 4
        if q.get("type") == "written":
            c.line(x + 12, y - 4, x + col_w, y - 4)
            y -= 20
        else:
            c.setFont(body, opt_fs)
            for idx, opt in enumerate(opts):
                for ln in _wrap_w(c, f"{LABELS[idx]}. {opt}", body, opt_fs, col_w - 14):
                    c.drawString(x + 14, y, ln)
                    y -= opt_fs + 3
        y -= gap
    c.save()


def create_report_pdf(data, filename):
    """data = {score, correct, total, results:[{idx, question, user_ans, correct_ans, correct, feedback}]}"""
    c = canvas.Canvas(filename, pagesize=A4)
    w, h = A4
    title, body = _pick_fonts("round")

    c.setFont(title, 22)
    c.drawCentredString(w / 2, h - 50, "학습 리포트")
    c.setFont(title, 30)
    c.drawCentredString(w / 2, h - 100, f"{data.get('score', 0)}%")
    c.setFont(body, 12)
    c.drawCentredString(w / 2, h - 130, f"정답 {data.get('correct', 0)} / {data.get('total', 0)}")
    c.line(50, h - 150, w - 50, h - 150)

    y = h - 180
    c.setFont(title, 14)
    c.drawString(50, y, "문항별 리뷰")
    y -= 26

    for item in data.get("results", []):
        if not item:
            continue
        if y < 90:
            c.showPage()
            y = h - 50
        c.setFont(title, 10)
        c.setFillColor(black)
        for ln in _wrap_w(c, f"Q{item['idx']}. {item['question']}", title, 10, w - 100):
            c.drawString(50, y, ln)
            y -= 14
        c.setFont(body, 10)
        c.setFillColor(green if item.get("correct") else red)
        for ln in _wrap_w(c, f"내 답: {item.get('user_ans','')}", body, 10, w - 110):
            c.drawString(60, y, ln)
            y -= 12
        c.setFillColor(green)
        for ln in _wrap_w(c, f"정답: {item.get('correct_ans','')}", body, 10, w - 110):
            c.drawString(60, y, ln)
            y -= 12
        c.setFillColor(grey)
        c.setFont(body, 9)
        for ln in _wrap_w(c, f"해설: {item.get('feedback','')}", body, 9, w - 110):
            c.drawString(60, y, ln)
            y -= 11
        y -= 12
    c.save()


def create_progress_pdf(data, filename):
    """웹 리포트(report.html, 라이트 모드)처럼 디자인한 학습 진도 리포트 PDF.
    data = _build_report() 형태:
      {nickname, generated_at, totals{wordbooks,words,exams,attempts}, avg_score, best_score,
       trend[{score,created_at}], recent[{score,correct,total,created_at,exam_name}]}"""
    from datetime import datetime as _dt
    BLUE = Color(0x29 / 255, 0x79 / 255, 0xFF / 255)
    INK = Color(0.11, 0.11, 0.14)
    MUTED = Color(0.51, 0.53, 0.58)
    CARD = Color(0.96, 0.97, 0.99)
    LINE = Color(0.90, 0.91, 0.94)
    GREEN = Color(0.13, 0.70, 0.33)
    REDC = Color(0.94, 0.27, 0.27)

    c = canvas.Canvas(filename, pagesize=A4)
    w, h = A4
    title, body = _pick_fonts("round")
    ML = 44
    CW = w - 2 * ML

    def fmt_date(iso):
        try:
            return _dt.fromisoformat(str(iso).replace("Z", "+00:00")).strftime("%Y.%m.%d %H:%M")
        except Exception:
            return str(iso or "")[:16]

    # ---- 헤더 (상단 파란 바 + 제목) ----
    c.setFillColor(BLUE); c.rect(0, h - 6, w, 6, stroke=0, fill=1)
    y = h - 52
    c.setFillColor(INK); c.setFont(title, 21)
    c.drawString(ML, y, f"{data.get('nickname', '학습자')}님의 학습 리포트")
    c.setFont(body, 10); c.setFillColor(MUTED)
    c.drawString(ML, y - 18, f"생성일 {fmt_date(data.get('generated_at', ''))}  ·  VoQuiz")
    y -= 48

    # ---- KPI 카드 6개 (2행 x 3열) ----
    t = data.get("totals", {})
    kpis = [
        ("단어장", str(t.get("wordbooks", 0)), False),
        ("총 단어", str(t.get("words", 0)), False),
        ("시험지", str(t.get("exams", 0)), False),
        ("응시 횟수", str(t.get("attempts", 0)), False),
        ("평균 점수", f"{data.get('avg_score', 0)}%", True),
        ("최고 점수", f"{data.get('best_score', 0)}%", True),
    ]
    cols, gap, cardh = 3, 12, 58
    cardw = (CW - gap * (cols - 1)) / cols
    for i, (label, val, accent) in enumerate(kpis):
        r, ci = divmod(i, cols)
        cx = ML + (cardw + gap) * ci
        cy = y - (cardh + gap) * r - cardh
        c.setFillColor(CARD); c.setStrokeColor(LINE); c.setLineWidth(1)
        c.roundRect(cx, cy, cardw, cardh, 8, stroke=1, fill=1)
        c.setFillColor(BLUE if accent else INK); c.setFont(title, 19)
        c.drawCentredString(cx + cardw / 2, cy + 27, val)
        c.setFillColor(MUTED); c.setFont(body, 9)
        c.drawCentredString(cx + cardw / 2, cy + 12, label)
    y -= (cardh + gap) * 2 + 18

    # ---- 점수 추이 (라인 차트) ----
    trend = data.get("trend", [])
    c.setFillColor(INK); c.setFont(title, 13); c.drawString(ML, y, "점수 추이"); y -= 10
    chart_h = 132
    bx, by = ML, y - chart_h
    c.setFillColor(CARD); c.setStrokeColor(LINE); c.setLineWidth(1)
    c.roundRect(bx, by, CW, chart_h, 8, stroke=1, fill=1)
    if trend:
        pad = 18
        ix, iy, iw, ih = bx + pad + 12, by + pad, CW - 2 * pad - 12, chart_h - 2 * pad
        n = len(trend)
        c.setFont(body, 7)
        for v in (0, 50, 100):
            gy = iy + ih * v / 100
            c.setStrokeColor(LINE); c.setLineWidth(0.7); c.line(ix, gy, ix + iw, gy)
            c.setFillColor(MUTED); c.drawRightString(ix - 5, gy - 2.5, str(v))
        pts = [(ix + (iw * i / (n - 1) if n > 1 else iw / 2), iy + ih * (tr["score"] / 100))
               for i, tr in enumerate(trend)]
        c.setStrokeColor(BLUE); c.setLineWidth(2)
        for i in range(1, len(pts)):
            c.line(pts[i - 1][0], pts[i - 1][1], pts[i][0], pts[i][1])
        c.setFillColor(BLUE)
        for px, py in pts:
            c.circle(px, py, 2.3, stroke=0, fill=1)
    else:
        c.setFillColor(MUTED); c.setFont(body, 10)
        c.drawCentredString(bx + CW / 2, by + chart_h / 2, "아직 응시 기록이 없어요.")
    y = by - 24

    # ---- 최근 응시 ----
    c.setFillColor(INK); c.setFont(title, 13); c.drawString(ML, y, "최근 응시"); y -= 22
    recent = data.get("recent", [])
    if not recent:
        c.setFillColor(MUTED); c.setFont(body, 10); c.drawString(ML, y, "최근 응시한 시험이 없어요.")
    for r in recent[:8]:
        if y < 66:
            c.showPage(); y = h - 60
        score = r.get("score", 0)
        sc = GREEN if score >= 80 else (BLUE if score >= 50 else REDC)
        c.setFillColor(INK); c.setFont(body, 11)
        c.drawString(ML, y, str(r.get("exam_name", ""))[:36])
        c.setFillColor(MUTED); c.setFont(body, 8)
        c.drawString(ML, y - 13, f"{fmt_date(r.get('created_at', ''))}  ·  {r.get('correct', 0)}/{r.get('total', 0)}")
        c.setFillColor(sc); c.setFont(title, 14)
        c.drawRightString(w - ML, y - 4, f"{score}%")
        c.setStrokeColor(LINE); c.setLineWidth(0.7); c.line(ML, y - 22, w - ML, y - 22)
        y -= 32

    c.save()
